services:
  redis-node-0:
    image: docker.io/library/redis:8
    command: >
      redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf
      --cluster-node-timeout 5000 --appendonly yes --protected-mode no
    ports:
      - 7000:6379

  redis-node-1:
    image: docker.io/library/redis:8
    command: >
      redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf
      --cluster-node-timeout 5000 --appendonly yes --protected-mode no
    ports:
      - 7001:6379

  redis-node-2:
    image: docker.io/library/redis:8
    command: >
      redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf
      --cluster-node-timeout 5000 --appendonly yes --protected-mode no
    ports:
      - 7002:6379

  redis-node-3:
    image: docker.io/library/redis:8
    command: >
      redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf
      --cluster-node-timeout 5000 --appendonly yes --protected-mode no
    ports:
      - 7003:6379

  redis-node-4:
    image: docker.io/library/redis:8
    command: >
      redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf
      --cluster-node-timeout 5000 --appendonly yes --protected-mode no
    ports:
      - 7004:6379

  redis-node-5:
    image: docker.io/library/redis:8
    command: >
      redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf
      --cluster-node-timeout 5000 --appendonly yes --protected-mode no
    ports:
      - 7005:6379

  redis-cluster-init:
    image: docker.io/library/redis:8
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    entrypoint: /bin/sh
    command: >
      -c 'for node in redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5; do
            until redis-cli -h $$node ping >/dev/null; do sleep 1; done;
          done;
          redis-cli --cluster create redis-node-0:6379 redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 --cluster-replicas 1 --cluster-yes'
